name: unstable

on:
  push:
    branches:
      - main
    tags:
      - ciflow/unstable/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions: read-all

jobs:
  # There must be at least one job here to satisfy GitHub action workflow syntax
  introduction:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Introduce PyTorch unstable workflow
        run: |
          echo "PyTorch unstable workflow is used to host experimental or flaky jobs"
          echo " that needs to be run for every commit, but doesn't block PR merging"
          echo " as part of the stable pull or trunk workflows."
          echo
          echo "In addition, a new label called ciflow/unstable can be attached to the"
          echo " PR to trigger this workflow. That can be done either manually or"
          echo " automatically using PyTorch auto-label bot."
          echo
          echo "Once the jobs are deemed stable enough (% red signal < 5% and TTS < 3h),"
          echo " they can graduate and move back to pull or trunk."

  #
  # Experimental ARC jobs
  #

  linux-jammy-py3_8-gcc11-build:
    name: linux-jammy-py3.8-gcc11
    uses: ./.github/workflows/_linux-build-rg.yml
    with:
      build-environment: linux-jammy-py3.8-gcc11
      docker-image-name: pytorch-linux-jammy-py3.8-gcc11
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 3, runner: "linux.2xlarge" },
          { config: "docs_test", shard: 1, num_shards: 1,  runner: "linux.2xlarge" },
          { config: "jit_legacy", shard: 1, num_shards: 1, runner: "linux.2xlarge" },
          { config: "backwards_compat", shard: 1, num_shards: 1, runner: "linux.2xlarge" },
          { config: "distributed", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "distributed", shard: 2, num_shards: 2, runner: "linux.2xlarge" },
        ]}


  linux-jammy-py3_8-gcc11-no-ops:
    name: linux-jammy-py3.8-gcc11-no-ops
    uses: ./.github/workflows/_linux-build-rg.yml
    with:
      build-environment: linux-jammy-py3.8-gcc11-no-ops
      docker-image-name: pytorch-linux-jammy-py3.8-gcc11
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1 },
        ]}

  linux-jammy-py3_8-gcc11-pch:
    name: linux-jammy-py3.8-gcc11-pch
    uses: ./.github/workflows/_linux-build-rg.yml
    with:
      build-environment: linux-jammy-py3.8-gcc11-pch
      docker-image-name: pytorch-linux-jammy-py3.8-gcc11
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1 },
        ]}

  linux-focal-py3_8-clang10-onnx-build:
    name: linux-focal-py3.8-clang10-onnx
    uses: ./.github/workflows/_linux-build-rg.yml
    with:
      build-environment: linux-focal-py3.8-clang10-onnx
      docker-image-name: pytorch-linux-focal-py3-clang10-onnx
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.2xlarge" },
        ]}

  linux-jammy-py3_10-clang15-asan-build:
    name: linux-jammy-py3.10-clang15-asan
    uses: ./.github/workflows/_linux-build-rg.yml
    with:
      build-environment: linux-jammy-py3.10-clang15-asan
      docker-image-name: pytorch-linux-jammy-py3-clang15-asan
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 6, runner: "linux.4xlarge" },
          { config: "default", shard: 2, num_shards: 6, runner: "linux.4xlarge" },
          { config: "default", shard: 3, num_shards: 6, runner: "linux.4xlarge" },
          { config: "default", shard: 4, num_shards: 6, runner: "linux.4xlarge" },
          { config: "default", shard: 5, num_shards: 6, runner: "linux.4xlarge" },
          { config: "default", shard: 6, num_shards: 6, runner: "linux.4xlarge" },
        ]}
      sync-tag: asan-build-arc

  linux-focal-py3_8-clang10-build:
    name: linux-focal-py3.8-clang10
    uses: ./.github/workflows/_linux-build-rg.yml
    with:
      build-environment: linux-focal-py3.8-clang10
      docker-image-name: pytorch-linux-focal-py3.8-clang10
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 3, runner: "linux.2xlarge" },
          { config: "crossref", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "crossref", shard: 2, num_shards: 2, runner: "linux.2xlarge" },
          { config: "dynamo", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "dynamo", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "dynamo", shard: 3, num_shards: 3, runner: "linux.2xlarge" },
        ]}

  linux-focal-py3_11-clang10-build:
    name: linux-focal-py3.11-clang10
    uses: ./.github/workflows/_linux-build-rg.yml
    with:
      build-environment: linux-focal-py3.11-clang10
      docker-image-name: pytorch-linux-focal-py3.11-clang10
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 3, runner: "linux.2xlarge" },
          { config: "crossref", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "crossref", shard: 2, num_shards: 2, runner: "linux.2xlarge" },
          { config: "dynamo", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "dynamo", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "dynamo", shard: 3, num_shards: 3, runner: "linux.2xlarge" },
        ]}

  #
  # End of Experimental ARC jobs
  #